name: 🚀 Feature Request
description: Suggest new documentation or improvements
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement to our documentation!
        
        **Important**: This is an unofficial documentation project. For official Q CLI feature requests, please use the [official repository](https://github.com/aws/amazon-q-developer-cli/issues).

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature request solve?
      placeholder: Describe the problem or gap in documentation
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see added or changed?
      placeholder: Describe your proposed solution
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Documentation Category
      description: Which category does this request relate to?
      options:
        - Getting Started
        - Configuration
        - Features
        - Best Practices
        - Troubleshooting
        - Developer Guide
        - Reference
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe alternatives you've considered

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: Screenshots, examples, links, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kamogashira-sys/q-cli-docs/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
